"use client";

import { useEffect, useState, useMemo } from "react";
import { useApp, useT } from "@/lib/store";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { AgentAvatar } from "../mianx/AgentAvatar";
import { useSession } from "next-auth/react";
import {
  FolderKanban,
  CheckCircle2,
  FileBox,
  MessageSquare,
  PlusCircle,
  ArrowRight,
  Activity,
  Sparkles,
  Search,
  PlayCircle,
  Lightbulb,
  Heart,
  Clock,
  Bot,
  Upload,
  Rocket,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface Project {
  id: string;
  title: string;
  status: string;
  progress: number;
  projectType: string;
  updatedAt: string;
  agents: { agent: { name: string; icon: string; color: string; role: string } }[];
  _count: { tasks: number; messages: number; deliverables: number };
}

function getGreeting(): string {
  const hour = new Date().getHours();
  if (hour >= 5 && hour < 12) return "Good morning";
  if (hour >= 12 && hour < 17) return "Good afternoon";
  if (hour >= 17 && hour < 21) return "Good evening";
  return "Good night";
}

const recentActivity = [
  {
    id: "1",
    action: "Agent completed a design mockup",
    project: "Brand Redesign",
    time: "2 min ago",
    icon: Sparkles,
    color: "from-purple-500 to-violet-500",
  },
  {
    id: "2",
    action: "New deliverable uploaded",
    project: "Marketing Site",
    time: "15 min ago",
    icon: Upload,
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "3",
    action: "Project milestone reached at 75%",
    project: "Mobile App",
    time: "1 hour ago",
    icon: CheckCircle2,
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "4",
    action: "Agent sent a status update",
    project: "E-commerce Platform",
    time: "2 hours ago",
    icon: Bot,
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "5",
    action: "Project launched successfully",
    project: "Landing Page",
    time: "Yesterday",
    icon: Rocket,
    color: "from-orange-500 to-amber-500",
  },
];

const quickActions = [
  {
    key: "newProject",
    icon: PlusCircle,
    label: "New Project",
    desc: "Start creating with AI",
    color: "from-purple-500 to-violet-500",
  },
  {
    key: "projects",
    icon: Activity,
    label: "View Agents",
    desc: "See your AI team",
    color: "from-cyan-500 to-blue-500",
  },
  {
    key: "support",
    icon: Heart,
    label: "Get Support",
    desc: "We're here to help",
    color: "from-pink-500 to-rose-500",
  },
  {
    key: "tutorial",
    icon: PlayCircle,
    label: "Watch Tutorial",
    desc: "Learn in 2 minutes",
    color: "from-amber-500 to-orange-500",
  },
];

export function DashboardOverview() {
  const t = useT();
  const { navigate, setSelectedProject } = useApp();
  const { data: session } = useSession();
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [showHelpTip, setShowHelpTip] = useState(true);
  const [currentTip, setCurrentTip] = useState(0);

  const helpTips = [
    "Tip: Create a project to get started with AI-powered design!",
    "Tip: You can chat with agents directly inside any project.",
    "Tip: Use the search bar (Ctrl+K) to quickly navigate anywhere.",
    "Tip: Deliverables are auto-generated by your AI team.",
  ];

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentTip((prev) => (prev + 1) % helpTips.length);
    }, 5000);
    return () => clearInterval(interval);
  }, [helpTips.length]);

  useEffect(() => {
    fetch("/api/projects")
      .then((r) => r.json())
      .then((data) => {
        setProjects(data.projects || []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const active = projects.filter(
    (p) => !["COMPLETED", "CANCELLED"].includes(p.status),
  );
  const completed = projects.filter((p) => p.status === "COMPLETED");
  const totalDeliverables = projects.reduce(
    (sum, p) => sum + p._count.deliverables,
    0,
  );
  const totalMessages = projects.reduce(
    (sum, p) => sum + p._count.messages,
    0,
  );

  const filteredProjects = useMemo(() => {
    if (!searchQuery.trim()) return projects;
    const q = searchQuery.toLowerCase();
    return projects.filter(
      (p) =>
        p.title.toLowerCase().includes(q) ||
        p.projectType.toLowerCase().includes(q) ||
        p.status.toLowerCase().includes(q),
    );
  }, [projects, searchQuery]);

  const stats = [
    {
      label: t("dash.activeProjects"),
      value: active.length,
      icon: FolderKanban,
      color: "from-purple-500 to-violet-500",
    },
    {
      label: t("dash.completedProjects"),
      value: completed.length,
      icon: CheckCircle2,
      color: "from-green-500 to-emerald-500",
    },
    {
      label: t("dash.totalDeliverables"),
      value: totalDeliverables,
      icon: FileBox,
      color: "from-cyan-500 to-blue-500",
    },
    {
      label: t("dash.agentMessages"),
      value: totalMessages,
      icon: MessageSquare,
      color: "from-pink-500 to-rose-500",
    },
  ];

  const handleQuickAction = (key: string) => {
    if (key === "tutorial") {
      window.open("https://mianx.ai/docs/getting-started", "_blank");
      return;
    }
    navigate(key as "dashboard" | "projects" | "newProject" | "deliverables" | "support" | "settings");
  };

  const greeting = getGreeting();

  return (
    <div className="space-y-6">
      {/* Header with time-based greeting */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold">
            {greeting},{" "}
            <span className="gradient-text">
              {session?.user?.name?.split(" ")[0] || "there"}
            </span>{" "}
            👋
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Here&apos;s what your AI agents have been up to.
          </p>
        </div>
        <Button
          onClick={() => navigate("newProject")}
          className="btn-gradient text-white"
        >
          <PlusCircle className="mr-2 h-4 w-4" />
          {t("dash.newProject")}
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {stats.map((s, i) => (
          <motion.div
            key={s.label}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05 }}
          >
            <Card className="glass border-purple-500/10 p-5 card-hover">
              <div
                className={`inline-flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-to-br ${s.color} mb-3`}
              >
                <s.icon className="h-4 w-4 text-white" />
              </div>
              <div className="text-2xl font-bold">{s.value}</div>
              <div className="text-xs text-muted-foreground">{s.label}</div>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Quick Actions */}
      <div>
        <h2 className="text-lg font-semibold mb-3">Quick Actions</h2>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
          {quickActions.map((action, i) => (
            <motion.button
              key={action.key}
              initial={{ opacity: 0, y: 15 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.2 + i * 0.05 }}
              onClick={() => handleQuickAction(action.key)}
              className="group"
            >
              <Card className="glass border-purple-500/10 p-4 card-hover text-left h-full">
                <div
                  className={`inline-flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br ${action.color} mb-3 group-hover:scale-110 transition-transform`}
                >
                  <action.icon className="h-5 w-5 text-white" />
                </div>
                <div className="font-semibold text-sm">{action.label}</div>
                <div className="text-xs text-muted-foreground mt-0.5">
                  {action.desc}
                </div>
              </Card>
            </motion.button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Projects Section */}
        <div className="lg:col-span-2">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">{t("dash.projects")}</h2>
            {projects.length > 0 && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => navigate("projects")}
                className="text-xs"
              >
                {t("common.viewAll")}
                <ArrowRight className="ml-1 h-3 w-3" />
              </Button>
            )}
          </div>

          {/* Search / Filter */}
          {projects.length > 0 && (
            <div className="relative mb-4">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search projects..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-9 bg-purple-500/5 border-purple-500/10 focus:border-purple-500/30"
              />
            </div>
          )}

          {loading ? (
            <div className="space-y-3">
              {[1, 2, 3].map((i) => (
                <div
                  key={i}
                  className="h-32 glass rounded-lg animate-pulse"
                />
              ))}
            </div>
          ) : projects.length === 0 ? (
            /* Improved Empty State */
            <Card className="glass border-purple-500/10 overflow-hidden">
              <div className="p-8 sm:p-12 text-center">
                {/* Illustration-style visual */}
                <div className="relative mx-auto w-32 h-32 mb-6">
                  {/* Outer glow ring */}
                  <div className="absolute inset-0 rounded-full bg-gradient-to-br from-purple-500/20 to-cyan-500/20 animate-pulse" />
                  {/* Middle ring */}
                  <div className="absolute inset-3 rounded-full bg-gradient-to-br from-purple-500/10 to-cyan-500/10" />
                  {/* Inner circle */}
                  <div className="absolute inset-6 rounded-full bg-gradient-to-br from-purple-500/20 to-cyan-500/20 flex items-center justify-center">
                    <Sparkles className="h-10 w-10 text-purple-400" />
                  </div>
                  {/* Floating orbs */}
                  <motion.div
                    className="absolute -top-1 -right-1 h-6 w-6 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500"
                    animate={{ y: [0, -6, 0] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  />
                  <motion.div
                    className="absolute -bottom-1 -left-1 h-4 w-4 rounded-full bg-gradient-to-br from-pink-400 to-rose-500"
                    animate={{ y: [0, 4, 0] }}
                    transition={{ duration: 2.5, repeat: Infinity }}
                  />
                </div>
                <h3 className="font-bold text-xl mb-2">
                  {t("dash.noProjects")}
                </h3>
                <p className="text-sm text-muted-foreground mb-2 max-w-sm mx-auto">
                  Your creative canvas is waiting! Create your first project and
                  watch AI agents design, build, and deliver in record time.
                </p>
                <p className="text-xs text-purple-400/80 mb-6">
                  ⚡ It only takes 30 seconds to get started
                </p>
                <div className="flex flex-col sm:flex-row gap-3 justify-center">
                  <Button
                    onClick={() => navigate("newProject")}
                    className="btn-gradient text-white"
                  >
                    <PlusCircle className="mr-2 h-4 w-4" />
                    {t("dash.createProject")}
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() =>
                      window.open(
                        "https://mianx.ai/docs/getting-started",
                        "_blank",
                      )
                    }
                    className="border-purple-500/20"
                  >
                    <PlayCircle className="mr-2 h-4 w-4" />
                    Watch Tutorial
                  </Button>
                </div>
              </div>
            </Card>
          ) : (
            <div className="space-y-3">
              {filteredProjects.length === 0 ? (
                <div className="text-center py-8">
                  <Search className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
                  <p className="text-sm text-muted-foreground">
                    No projects match &quot;{searchQuery}&quot;
                  </p>
                </div>
              ) : (
                filteredProjects.slice(0, 5).map((p) => (
                  <Card
                    key={p.id}
                    className="glass border-purple-500/10 p-5 card-hover cursor-pointer"
                    onClick={() => {
                      setSelectedProject(p.id);
                      navigate("projectDetail", { id: p.id });
                    }}
                  >
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <h3 className="font-semibold truncate">{p.title}</h3>
                          <Badge
                            variant="outline"
                            className="text-xs glass flex-shrink-0"
                          >
                            {p.projectType}
                          </Badge>
                        </div>
                        <p className="text-xs text-muted-foreground mb-3">
                          Last updated{" "}
                          {new Date(p.updatedAt).toLocaleDateString()}
                        </p>
                        <div className="flex items-center gap-3 mb-3">
                          <div className="flex -space-x-2">
                            {p.agents.slice(0, 5).map((a, i) => (
                              <div
                                key={i}
                                className="ring-2 ring-background rounded-full"
                              >
                                <AgentAvatar
                                  name={a.agent.name}
                                  icon={a.agent.icon}
                                  color={a.agent.color}
                                  size="sm"
                                />
                              </div>
                            ))}
                            {p.agents.length > 5 && (
                              <div className="flex h-8 w-8 items-center justify-center rounded-full bg-muted text-xs font-medium ring-2 ring-background">
                                +{p.agents.length - 5}
                              </div>
                            )}
                          </div>
                          <span className="text-xs text-muted-foreground">
                            {p.agents.length} agents ·{" "}
                            {p._count.tasks} tasks ·{" "}
                            {p._count.deliverables} deliverables
                          </span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Progress
                            value={p.progress}
                            className="h-1.5 flex-1"
                          />
                          <span className="text-xs text-muted-foreground w-10 text-right">
                            {p.progress}%
                          </span>
                        </div>
                      </div>
                    </div>
                  </Card>
                ))
              )}
            </div>
          )}
        </div>

        {/* Recent Activity Sidebar */}
        <div className="lg:col-span-1">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold">Recent Activity</h2>
            <Badge variant="outline" className="text-xs glass">
              <Clock className="mr-1 h-3 w-3" />
              Live
            </Badge>
          </div>
          <Card className="glass border-purple-500/10 p-4">
            <div className="space-y-4 max-h-96 overflow-y-auto">
              {recentActivity.map((item, i) => (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, x: 10 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ delay: 0.3 + i * 0.08 }}
                  className="flex gap-3"
                >
                  <div
                    className={`flex-shrink-0 h-8 w-8 rounded-lg bg-gradient-to-br ${item.color} flex items-center justify-center`}
                  >
                    <item.icon className="h-4 w-4 text-white" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium leading-tight">
                      {item.action}
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {item.project} · {item.time}
                    </p>
                  </div>
                </motion.div>
              ))}
            </div>
          </Card>
        </div>
      </div>

      {/* Floating Help Button */}
      <AnimatePresence>
        {showHelpTip && (
          <motion.div
            initial={{ opacity: 0, y: 20, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.9 }}
            className="fixed bottom-6 right-6 z-50 flex flex-col items-end gap-2"
          >
            {/* Tooltip card */}
            <motion.div
              key={currentTip}
              initial={{ opacity: 0, y: 5 }}
              animate={{ opacity: 1, y: 0 }}
              className="glass border-purple-500/20 rounded-lg px-4 py-3 max-w-xs shadow-lg"
            >
              <div className="flex items-start gap-2">
                <Lightbulb className="h-4 w-4 text-amber-400 mt-0.5 flex-shrink-0" />
                <p className="text-sm">{helpTips[currentTip]}</p>
              </div>
            </motion.div>
            {/* Button */}
            <button
              onClick={() => setShowHelpTip(false)}
              title="Dismiss help tips"
              className="h-12 w-12 rounded-full bg-gradient-to-br from-purple-500 to-cyan-500 text-white shadow-lg hover:shadow-xl hover:scale-105 transition-all flex items-center justify-center"
            >
              <Lightbulb className="h-5 w-5" />
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Always-visible small help button when tip is dismissed */}
      {!showHelpTip && (
        <motion.button
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          onClick={() => setShowHelpTip(true)}
          title="Show help tips"
          className="fixed bottom-6 right-6 z-50 h-10 w-10 rounded-full glass border-purple-500/20 text-purple-400 hover:text-purple-300 hover:bg-purple-500/10 transition-colors flex items-center justify-center"
        >
          <Lightbulb className="h-4 w-4" />
        </motion.button>
      )}
    </div>
  );
}
