"use client";

import { useEffect, useState } from "react";
import { useApp } from "@/lib/store";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  FileBox,
  Loader2,
  Download,
  FileCode,
  FileText,
  Image as ImageIcon,
  ScrollText,
} from "lucide-react";
import { toast } from "sonner";

interface Deliverable {
  id: string;
  title: string;
  description: string | null;
  fileType: string;
  content: string;
  fileName: string | null;
  createdAt: string;
  project: { id: string; title: string };
  uploader: { name: string };
}

const FILE_ICONS: Record<string, typeof FileCode> = {
  code: FileCode,
  document: FileText,
  design: ImageIcon,
  report: ScrollText,
  archive: FileBox,
};

export function DeliverablesList() {
  const { navigate, setSelectedProject } = useApp();
  const [deliverables, setDeliverables] = useState<Deliverable[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Fetch all deliverables by getting all projects then their deliverables
    fetch("/api/projects")
      .then((r) => r.json())
      .then(async (data) => {
        const projects = data.projects || [];
        const allDeliverables: Deliverable[] = [];

        for (const p of projects) {
          if (p._count.deliverables > 0) {
            const res = await fetch(
              `/api/deliverables?projectId=${p.id}`,
            );
            const dData = await res.json();
            if (dData.deliverables) {
              allDeliverables.push(
                ...dData.deliverables.map(
                  (d: Deliverable) => ({
                    ...d,
                    project: { id: p.id, title: p.title },
                  }),
                ),
              );
            }
          }
        }

        // Sort by date desc
        allDeliverables.sort(
          (a, b) =>
            new Date(b.createdAt).getTime() -
            new Date(a.createdAt).getTime(),
        );

        setDeliverables(allDeliverables);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  const handleDownload = (d: Deliverable) => {
    const blob = new Blob([d.content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = d.fileName || `${d.title}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success("Downloaded!");
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl sm:text-3xl font-bold">Deliverables Vault</h1>
        <p className="text-sm text-muted-foreground mt-1">
          All files generated by your AI agents across all projects.
        </p>
      </div>

      {loading ? (
        <div className="flex justify-center py-12">
          <Loader2 className="h-6 w-6 animate-spin text-purple-400" />
        </div>
      ) : deliverables.length === 0 ? (
        <Card className="glass border-purple-500/10 p-12 text-center">
          <FileBox className="mx-auto h-12 w-12 text-muted-foreground/50 mb-4" />
          <h3 className="font-semibold text-lg mb-2">No deliverables yet</h3>
          <p className="text-sm text-muted-foreground mb-4">
            Create a project and ask your agents to generate deliverables.
          </p>
          <Button
            onClick={() => navigate("newProject")}
            className="btn-gradient text-white"
          >
            Start a Project
          </Button>
        </Card>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {deliverables.map((d) => {
            const FileIcon = FILE_ICONS[d.fileType] || FileText;
            return (
              <Card
                key={d.id}
                className="glass border-purple-500/10 p-5 card-hover cursor-pointer"
                onClick={() => {
                  setSelectedProject(d.project.id);
                  navigate("projectDetail", { id: d.project.id });
                }}
              >
                <div className="flex items-start gap-3 mb-3">
                  <div className="flex-shrink-0 flex h-11 w-11 items-center justify-center rounded-lg bg-gradient-to-br from-purple-500/20 to-cyan-500/20">
                    <FileIcon className="h-5 w-5 text-purple-300" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-medium text-sm truncate">{d.title}</h3>
                    <Badge
                      variant="outline"
                      className="text-xs glass capitalize mt-1"
                    >
                      {d.fileType}
                    </Badge>
                  </div>
                </div>
                <p className="text-xs text-muted-foreground line-clamp-2 mb-3">
                  {d.description || d.content.slice(0, 120) + "..."}
                </p>
                <div className="flex items-center justify-between text-xs text-muted-foreground mb-3">
                  <span className="truncate">{d.project.title}</span>
                  <span>{new Date(d.createdAt).toLocaleDateString()}</span>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDownload(d);
                  }}
                  className="w-full glass"
                >
                  <Download className="mr-1 h-3 w-3" />
                  Download
                </Button>
              </Card>
            );
          })}
        </div>
      )}
    </div>
  );
}
